name: App E2E CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "master"

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: "http://localhost:8080"
          browser: chrome
          headless: true
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos