name: App Quality Check E2E CI

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress debug logs 📝
        uses: ./
        env:
          DEBUG: '@cypress/github-action'
        with:
          working-directory: ./
