name: Make a new release

on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose -f "release.docker-compose.yml" up -d --build
      - name: Build Docker image
        run: docker build -t my-image .
      - name: Copy APK file
        run: docker create --name tmp my-image
      - name: Copy file
        run: docker cp tmp:/app/tempory/app-debug.apk .
      - name: Remove tmp
        run: docker rm -f tmp
      - name: Release APK on GitHub
        uses: actions/upload-release-asset@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
          file: app-debug.apk

      - name: Stop containers
        if: always()
        run: docker-compose -f "release.docker-compose.yml" down