name: Make a new release


on: [push]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose -f "release.docker-compose.yml" up -d --build

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down